# Login
POST http://127.0.0.1:8000/api/v1/auth/login
Content-Type: application/json

{
  "email": "therapist@mail.com",
  "password": "password123"
}

###

# List participants
GET http://127.0.0.1:8000/api/v1/participants
Accept: application/json
